[package]
name = "home-audio-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
cpal = "0.15.2"
prost = "0.11.9"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"
