# vim:ft=yaml.ansible
- name: Home Server Setup
  hosts: localhost
  connection: local

  vars:
    home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - gcc
          - htop
          - curl
          - neovim
          - openssh-client
          - bluez-alsa-utils
          - nodejs
          - npm
          - libasound2
          - libasound2-dev
          - libudev-dev
          - pkg-config
      become: true

    - name: Copy ALSA config
      ansible.builtin.copy:
        src: "./.asoundrc"
        dest: "{{ home_dir }}/.asoundrc"
        mode: "0777"

    - name: Download GitHub SSH keys
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Jackboxx/dotfiles/main/private/personal-keys/github_ed25519"
        dest: "/tmp/github_ed25519"
        mode: "0666"

    - name: Decrypt GitHub SSH keys
      ansible.builtin.copy:
        src: "/tmp/github_ed25519"
        dest: "{{ home_dir }}/.ssh/github_ed25519"
        mode: "0600"
        decrypt: true
