#!/bin/sh

tmux neww $1
tmux split-window -h $2
tmux send-keys 'C-m'
tmux split-window -v -t 0 $3
tmux send-keys 'C-m'
tmux split-window -v -t 1 $4

tmux neww $5
tmux split-window -h $6
tmux send-keys 'C-m'
tmux split-window -v -t 0 $7
tmux send-keys 'C-m'
tmux split-window -v -t 1 $8
