// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetaData } from "./AudioMetaData";

export interface AddQueueItemParams { metadata: AudioMetaData, url: string, }