// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioNodeHealth } from "./AudioNodeHealth";

export interface AudioNodeInfo { source_name: string, human_readable_name: string, health: AudioNodeHealth, }