// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioNodeHealthMild } from './AudioNodeHealthMild';
import type { AudioNodeHealthPoor } from './AudioNodeHealthPoor';

export type AudioNodeHealth =
	| 'good'
	| { mild: AudioNodeHealthMild }
	| { poor: AudioNodeHealthPoor };
