// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackInfo } from './PlaybackInfo';
import type { ProcessorInfo } from './ProcessorInfo';

export interface AudioStateInfo {
	playbackInfo: PlaybackInfo;
	processorInfo: ProcessorInfo;
}
