// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetaData } from './AudioMetaData';
import type { AudioNodeHealth } from './AudioNodeHealth';
import type { AudioStateInfo } from './AudioStateInfo';
import type { DownloadIdentifier } from './DownloadIdentifier';
import type { ErrorResponse } from './ErrorResponse';

export type AudioNodeInfoStreamMessage =
	| { QUEUE: Array<AudioMetaData> }
	| { HEALTH: AudioNodeHealth }
	| {
			DOWNLOAD: {
				active: Array<DownloadIdentifier>;
				failed: Record<DownloadIdentifier, ErrorResponse>;
			};
	  }
	| { AUDIO_STATE_INFO: AudioStateInfo };
