// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioNodeHealthPoor = "device-not-available" | "audio-stream-read-failed" | { "audio-backend-error": string };