// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AudioMetaData {
	name: string;
	author: string | null;
	duration: bigint | null;
	thumbnail_url: string | null;
}
