// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetadata } from "./AudioMetadata";
import type { AudioNodeHealth } from "./AudioNodeHealth";
import type { AudioStateInfo } from "./AudioStateInfo";
import type { RunningDownloadInfo } from "./RunningDownloadInfo";

export type AudioNodeInfoStreamMessage = { "QUEUE": Array<AudioMetadata> } | { "HEALTH": AudioNodeHealth } | { "DOWNLOAD": RunningDownloadInfo } | { "AUDIO_STATE_INFO": AudioStateInfo };