// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddQueueItemParams } from './AddQueueItemParams';
import type { LoopQueueParams } from './LoopQueueParams';
import type { MoveQueueItemParams } from './MoveQueueItemParams';
import type { PlaySelectedParams } from './PlaySelectedParams';
import type { RemoveQueueItemParams } from './RemoveQueueItemParams';
import type { SetAudioProgressParams } from './SetAudioProgressParams';
import type { SetAudioVolumeParams } from './SetAudioVolumeParams';

export type AudioNodeCommand =
	| { ADD_QUEUE_ITEM: AddQueueItemParams }
	| { REMOVE_QUEUE_ITEM: RemoveQueueItemParams }
	| { MOVE_QUEUE_ITEM: MoveQueueItemParams }
	| { SET_AUDIO_VOLUME: SetAudioVolumeParams }
	| { SET_AUDIO_PROGRESS: SetAudioProgressParams }
	| 'PAUSE_QUEUE'
	| 'UN_PAUSE_QUEUE'
	| 'PLAY_NEXT'
	| 'PLAY_PREVIOUS'
	| { PLAY_SELECTED: PlaySelectedParams }
	| { LOOP_QUEUE: LoopQueueParams };
