// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrainSessionWsResponse = { "SESSION_CONNECTED_RESPONSE": { node_info: Array<AudioNodeInfo>, } };