// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadInfo = { "you-tube-video": { url: string, } } | { "you-tube-playlist": { playlist_url: string, video_urls: Array<string>, } };