// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadIdentifier } from "./DownloadIdentifier";
import type { ErrorResponse } from "./ErrorResponse";

export interface DownloadInfo { active: Array<DownloadIdentifier>, failed: Array<[DownloadIdentifier, ErrorResponse]>, }