// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadInfo = { "youtube-video": { url: string, } } | { "youtube-playlist": { playlist_url: string, video_urls: Array<string>, } };