// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopBounds } from "./LoopBounds";

export interface LoopQueueParams { bounds: LoopBounds | null, }