// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioNodeHealth } from "./AudioNodeHealth";
import type { AudioStateInfo } from "./AudioStateInfo";
import type { RunningDownloadInfo } from "./RunningDownloadInfo";

export type NodeSessionWsResponse = { "SESSION_CONNECTED_RESPONSE": { QUEUE: Array<AudioMetadata>, HEALTH: AudioNodeHealth | null, DOWNLOADS: RunningDownloadInfo | null, AUDIO_STATE_INFO: AudioStateInfo | null, } };