// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PlaylistMetadata { name: string | null, author: string | null, cover_art_url: string | null, }