// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackState } from './PlaybackState';

export interface ProcessorInfo {
	playbackState: PlaybackState;
	audioProgress: number;
	audioVolume: number;
}
