#!/bin/sh

./fake-alsa/target/release/fake-alsa conf-cava -a 4 -o "./fake-alsa/cava"

parallel "./api-cli/target/release/audio-manager-api-cli send node -s dummy_out_{} add-queue-item -n 'the pretender' -u 'https://www.youtube.com/watch?v=SBjQ9tuuTJQ'" ::: {0..3} && \
    ./tile-tmux \
        'cava -p ./fake-alsa/cava/config_0'  \
        'cava -p ./fake-alsa/cava/config_1'  \
        'cava -p ./fake-alsa/cava/config_2'  \
        'cava -p ./fake-alsa/cava/config_3'  \
