// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetaData } from "./AudioMetaData";
import type { AudioNodeHealth } from "./AudioNodeHealth";
import type { AudioStateInfo } from "./AudioStateInfo";
import type { DownloadInfo } from "./DownloadInfo";

export type AudioNodeInfoStreamMessage = { "QUEUE": Array<AudioMetaData> } | { "HEALTH": AudioNodeHealth } | { "DOWNLOAD": DownloadInfo } | { "AUDIO_STATE_INFO": AudioStateInfo };