// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetaData } from "./AudioMetaData";
import type { AudioNodeHealth } from "./AudioNodeHealth";

export type NodeSessionWsResponse = { "SESSION_CONNECTED_RESPONSE": { queue: Array | null, health: AudioNodeHealth | null, } };