version: '3'

services:
  audio-database:
    image: 'postgres:latest'
    ports:
      - 50001:5432
    env_file:
      - .env-postgres
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
networks: 
  postgres-network:
    driver: bridge
